/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifTravailRouteImport } from './routes/verif-travail'
import { Route as VerifClasseurRouteImport } from './routes/verif-classeur'
import { Route as SuiviRouteImport } from './routes/suivi'
import { Route as ScanEleveRouteImport } from './routes/scan-eleve'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ImportExportRouteImport } from './routes/import-export'
import { Route as HistoriqueRouteImport } from './routes/historique'
import { Route as EmploiDuTempsRouteImport } from './routes/emploi-du-temps'
import { Route as AeshRouteImport } from './routes/aesh'
import { Route as AbsencesRouteImport } from './routes/absences'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifTravailIndexRouteImport } from './routes/verif-travail.index'
import { Route as VerifClasseurIndexRouteImport } from './routes/verif-classeur.index'
import { Route as QrCodesIndexRouteImport } from './routes/qr-codes.index'
import { Route as BilanClasseIndexRouteImport } from './routes/bilan-classe.index'
import { Route as VerifTravailClasseIdRouteImport } from './routes/verif-travail.$classeId'
import { Route as VerifTravailClasseClasseIdRouteImport } from './routes/verif-travail-classe.$classeId'
import { Route as VerifClasseurClasseIdRouteImport } from './routes/verif-classeur.$classeId'
import { Route as QrCodesClasseIdRouteImport } from './routes/qr-codes.$classeId'
import { Route as PlanClasseIdRouteImport } from './routes/plan.$classeId'
import { Route as ElevesEleveIdRouteImport } from './routes/eleves.$eleveId'
import { Route as ClassesClasseIdRouteImport } from './routes/classes.$classeId'
import { Route as BilanEleveIdRouteImport } from './routes/bilan.$eleveId'
import { Route as BilanClasseClasseIdRouteImport } from './routes/bilan-classe.$classeId'
import { Route as BavardagesClasseIdRouteImport } from './routes/bavardages.$classeId'
import { Route as AppelClasseIdRouteImport } from './routes/appel.$classeId'
import { Route as AppelPlanClasseIdRouteImport } from './routes/appel-plan.$classeId'
import { Route as ElevesEleveIdElevesNestedEleveIdRouteImport } from './routes/eleves.$eleveId.eleves.$nestedEleveId'
import { Route as ApiPublicIcsTokenRouteImport } from './routes/api/public/ics.$token'

const VerifTravailRoute = VerifTravailRouteImport.update({
  id: '/verif-travail',
  path: '/verif-travail',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifClasseurRoute = VerifClasseurRouteImport.update({
  id: '/verif-classeur',
  path: '/verif-classeur',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiviRoute = SuiviRouteImport.update({
  id: '/suivi',
  path: '/suivi',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanEleveRoute = ScanEleveRouteImport.update({
  id: '/scan-eleve',
  path: '/scan-eleve',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportExportRoute = ImportExportRouteImport.update({
  id: '/import-export',
  path: '/import-export',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriqueRoute = HistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const EmploiDuTempsRoute = EmploiDuTempsRouteImport.update({
  id: '/emploi-du-temps',
  path: '/emploi-du-temps',
  getParentRoute: () => rootRouteImport,
} as any)
const AeshRoute = AeshRouteImport.update({
  id: '/aesh',
  path: '/aesh',
  getParentRoute: () => rootRouteImport,
} as any)
const AbsencesRoute = AbsencesRouteImport.update({
  id: '/absences',
  path: '/absences',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifTravailIndexRoute = VerifTravailIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VerifTravailRoute,
} as any)
const VerifClasseurIndexRoute = VerifClasseurIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VerifClasseurRoute,
} as any)
const QrCodesIndexRoute = QrCodesIndexRouteImport.update({
  id: '/qr-codes/',
  path: '/qr-codes/',
  getParentRoute: () => rootRouteImport,
} as any)
const BilanClasseIndexRoute = BilanClasseIndexRouteImport.update({
  id: '/bilan-classe/',
  path: '/bilan-classe/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifTravailClasseIdRoute = VerifTravailClasseIdRouteImport.update({
  id: '/$classeId',
  path: '/$classeId',
  getParentRoute: () => VerifTravailRoute,
} as any)
const VerifTravailClasseClasseIdRoute =
  VerifTravailClasseClasseIdRouteImport.update({
    id: '/verif-travail-classe/$classeId',
    path: '/verif-travail-classe/$classeId',
    getParentRoute: () => rootRouteImport,
  } as any)
const VerifClasseurClasseIdRoute = VerifClasseurClasseIdRouteImport.update({
  id: '/$classeId',
  path: '/$classeId',
  getParentRoute: () => VerifClasseurRoute,
} as any)
const QrCodesClasseIdRoute = QrCodesClasseIdRouteImport.update({
  id: '/qr-codes/$classeId',
  path: '/qr-codes/$classeId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanClasseIdRoute = PlanClasseIdRouteImport.update({
  id: '/plan/$classeId',
  path: '/plan/$classeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ElevesEleveIdRoute = ElevesEleveIdRouteImport.update({
  id: '/eleves/$eleveId',
  path: '/eleves/$eleveId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesClasseIdRoute = ClassesClasseIdRouteImport.update({
  id: '/classes/$classeId',
  path: '/classes/$classeId',
  getParentRoute: () => rootRouteImport,
} as any)
const BilanEleveIdRoute = BilanEleveIdRouteImport.update({
  id: '/bilan/$eleveId',
  path: '/bilan/$eleveId',
  getParentRoute: () => rootRouteImport,
} as any)
const BilanClasseClasseIdRoute = BilanClasseClasseIdRouteImport.update({
  id: '/bilan-classe/$classeId',
  path: '/bilan-classe/$classeId',
  getParentRoute: () => rootRouteImport,
} as any)
const BavardagesClasseIdRoute = BavardagesClasseIdRouteImport.update({
  id: '/bavardages/$classeId',
  path: '/bavardages/$classeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppelClasseIdRoute = AppelClasseIdRouteImport.update({
  id: '/appel/$classeId',
  path: '/appel/$classeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppelPlanClasseIdRoute = AppelPlanClasseIdRouteImport.update({
  id: '/appel-plan/$classeId',
  path: '/appel-plan/$classeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ElevesEleveIdElevesNestedEleveIdRoute =
  ElevesEleveIdElevesNestedEleveIdRouteImport.update({
    id: '/eleves/$nestedEleveId',
    path: '/eleves/$nestedEleveId',
    getParentRoute: () => ElevesEleveIdRoute,
  } as any)
const ApiPublicIcsTokenRoute = ApiPublicIcsTokenRouteImport.update({
  id: '/api/public/ics/$token',
  path: '/api/public/ics/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/absences': typeof AbsencesRoute
  '/aesh': typeof AeshRoute
  '/emploi-du-temps': typeof EmploiDuTempsRoute
  '/historique': typeof HistoriqueRoute
  '/import-export': typeof ImportExportRoute
  '/scan': typeof ScanRoute
  '/scan-eleve': typeof ScanEleveRoute
  '/suivi': typeof SuiviRoute
  '/verif-classeur': typeof VerifClasseurRouteWithChildren
  '/verif-travail': typeof VerifTravailRouteWithChildren
  '/appel-plan/$classeId': typeof AppelPlanClasseIdRoute
  '/appel/$classeId': typeof AppelClasseIdRoute
  '/bavardages/$classeId': typeof BavardagesClasseIdRoute
  '/bilan-classe/$classeId': typeof BilanClasseClasseIdRoute
  '/bilan/$eleveId': typeof BilanEleveIdRoute
  '/classes/$classeId': typeof ClassesClasseIdRoute
  '/eleves/$eleveId': typeof ElevesEleveIdRouteWithChildren
  '/plan/$classeId': typeof PlanClasseIdRoute
  '/qr-codes/$classeId': typeof QrCodesClasseIdRoute
  '/verif-classeur/$classeId': typeof VerifClasseurClasseIdRoute
  '/verif-travail-classe/$classeId': typeof VerifTravailClasseClasseIdRoute
  '/verif-travail/$classeId': typeof VerifTravailClasseIdRoute
  '/bilan-classe/': typeof BilanClasseIndexRoute
  '/qr-codes/': typeof QrCodesIndexRoute
  '/verif-classeur/': typeof VerifClasseurIndexRoute
  '/verif-travail/': typeof VerifTravailIndexRoute
  '/api/public/ics/$token': typeof ApiPublicIcsTokenRoute
  '/eleves/$eleveId/eleves/$nestedEleveId': typeof ElevesEleveIdElevesNestedEleveIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/absences': typeof AbsencesRoute
  '/aesh': typeof AeshRoute
  '/emploi-du-temps': typeof EmploiDuTempsRoute
  '/historique': typeof HistoriqueRoute
  '/import-export': typeof ImportExportRoute
  '/scan': typeof ScanRoute
  '/scan-eleve': typeof ScanEleveRoute
  '/suivi': typeof SuiviRoute
  '/appel-plan/$classeId': typeof AppelPlanClasseIdRoute
  '/appel/$classeId': typeof AppelClasseIdRoute
  '/bavardages/$classeId': typeof BavardagesClasseIdRoute
  '/bilan-classe/$classeId': typeof BilanClasseClasseIdRoute
  '/bilan/$eleveId': typeof BilanEleveIdRoute
  '/classes/$classeId': typeof ClassesClasseIdRoute
  '/eleves/$eleveId': typeof ElevesEleveIdRouteWithChildren
  '/plan/$classeId': typeof PlanClasseIdRoute
  '/qr-codes/$classeId': typeof QrCodesClasseIdRoute
  '/verif-classeur/$classeId': typeof VerifClasseurClasseIdRoute
  '/verif-travail-classe/$classeId': typeof VerifTravailClasseClasseIdRoute
  '/verif-travail/$classeId': typeof VerifTravailClasseIdRoute
  '/bilan-classe': typeof BilanClasseIndexRoute
  '/qr-codes': typeof QrCodesIndexRoute
  '/verif-classeur': typeof VerifClasseurIndexRoute
  '/verif-travail': typeof VerifTravailIndexRoute
  '/api/public/ics/$token': typeof ApiPublicIcsTokenRoute
  '/eleves/$eleveId/eleves/$nestedEleveId': typeof ElevesEleveIdElevesNestedEleveIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/absences': typeof AbsencesRoute
  '/aesh': typeof AeshRoute
  '/emploi-du-temps': typeof EmploiDuTempsRoute
  '/historique': typeof HistoriqueRoute
  '/import-export': typeof ImportExportRoute
  '/scan': typeof ScanRoute
  '/scan-eleve': typeof ScanEleveRoute
  '/suivi': typeof SuiviRoute
  '/verif-classeur': typeof VerifClasseurRouteWithChildren
  '/verif-travail': typeof VerifTravailRouteWithChildren
  '/appel-plan/$classeId': typeof AppelPlanClasseIdRoute
  '/appel/$classeId': typeof AppelClasseIdRoute
  '/bavardages/$classeId': typeof BavardagesClasseIdRoute
  '/bilan-classe/$classeId': typeof BilanClasseClasseIdRoute
  '/bilan/$eleveId': typeof BilanEleveIdRoute
  '/classes/$classeId': typeof ClassesClasseIdRoute
  '/eleves/$eleveId': typeof ElevesEleveIdRouteWithChildren
  '/plan/$classeId': typeof PlanClasseIdRoute
  '/qr-codes/$classeId': typeof QrCodesClasseIdRoute
  '/verif-classeur/$classeId': typeof VerifClasseurClasseIdRoute
  '/verif-travail-classe/$classeId': typeof VerifTravailClasseClasseIdRoute
  '/verif-travail/$classeId': typeof VerifTravailClasseIdRoute
  '/bilan-classe/': typeof BilanClasseIndexRoute
  '/qr-codes/': typeof QrCodesIndexRoute
  '/verif-classeur/': typeof VerifClasseurIndexRoute
  '/verif-travail/': typeof VerifTravailIndexRoute
  '/api/public/ics/$token': typeof ApiPublicIcsTokenRoute
  '/eleves/$eleveId/eleves/$nestedEleveId': typeof ElevesEleveIdElevesNestedEleveIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/absences'
    | '/aesh'
    | '/emploi-du-temps'
    | '/historique'
    | '/import-export'
    | '/scan'
    | '/scan-eleve'
    | '/suivi'
    | '/verif-classeur'
    | '/verif-travail'
    | '/appel-plan/$classeId'
    | '/appel/$classeId'
    | '/bavardages/$classeId'
    | '/bilan-classe/$classeId'
    | '/bilan/$eleveId'
    | '/classes/$classeId'
    | '/eleves/$eleveId'
    | '/plan/$classeId'
    | '/qr-codes/$classeId'
    | '/verif-classeur/$classeId'
    | '/verif-travail-classe/$classeId'
    | '/verif-travail/$classeId'
    | '/bilan-classe/'
    | '/qr-codes/'
    | '/verif-classeur/'
    | '/verif-travail/'
    | '/api/public/ics/$token'
    | '/eleves/$eleveId/eleves/$nestedEleveId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/absences'
    | '/aesh'
    | '/emploi-du-temps'
    | '/historique'
    | '/import-export'
    | '/scan'
    | '/scan-eleve'
    | '/suivi'
    | '/appel-plan/$classeId'
    | '/appel/$classeId'
    | '/bavardages/$classeId'
    | '/bilan-classe/$classeId'
    | '/bilan/$eleveId'
    | '/classes/$classeId'
    | '/eleves/$eleveId'
    | '/plan/$classeId'
    | '/qr-codes/$classeId'
    | '/verif-classeur/$classeId'
    | '/verif-travail-classe/$classeId'
    | '/verif-travail/$classeId'
    | '/bilan-classe'
    | '/qr-codes'
    | '/verif-classeur'
    | '/verif-travail'
    | '/api/public/ics/$token'
    | '/eleves/$eleveId/eleves/$nestedEleveId'
  id:
    | '__root__'
    | '/'
    | '/absences'
    | '/aesh'
    | '/emploi-du-temps'
    | '/historique'
    | '/import-export'
    | '/scan'
    | '/scan-eleve'
    | '/suivi'
    | '/verif-classeur'
    | '/verif-travail'
    | '/appel-plan/$classeId'
    | '/appel/$classeId'
    | '/bavardages/$classeId'
    | '/bilan-classe/$classeId'
    | '/bilan/$eleveId'
    | '/classes/$classeId'
    | '/eleves/$eleveId'
    | '/plan/$classeId'
    | '/qr-codes/$classeId'
    | '/verif-classeur/$classeId'
    | '/verif-travail-classe/$classeId'
    | '/verif-travail/$classeId'
    | '/bilan-classe/'
    | '/qr-codes/'
    | '/verif-classeur/'
    | '/verif-travail/'
    | '/api/public/ics/$token'
    | '/eleves/$eleveId/eleves/$nestedEleveId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbsencesRoute: typeof AbsencesRoute
  AeshRoute: typeof AeshRoute
  EmploiDuTempsRoute: typeof EmploiDuTempsRoute
  HistoriqueRoute: typeof HistoriqueRoute
  ImportExportRoute: typeof ImportExportRoute
  ScanRoute: typeof ScanRoute
  ScanEleveRoute: typeof ScanEleveRoute
  SuiviRoute: typeof SuiviRoute
  VerifClasseurRoute: typeof VerifClasseurRouteWithChildren
  VerifTravailRoute: typeof VerifTravailRouteWithChildren
  AppelPlanClasseIdRoute: typeof AppelPlanClasseIdRoute
  AppelClasseIdRoute: typeof AppelClasseIdRoute
  BavardagesClasseIdRoute: typeof BavardagesClasseIdRoute
  BilanClasseClasseIdRoute: typeof BilanClasseClasseIdRoute
  BilanEleveIdRoute: typeof BilanEleveIdRoute
  ClassesClasseIdRoute: typeof ClassesClasseIdRoute
  ElevesEleveIdRoute: typeof ElevesEleveIdRouteWithChildren
  PlanClasseIdRoute: typeof PlanClasseIdRoute
  QrCodesClasseIdRoute: typeof QrCodesClasseIdRoute
  VerifTravailClasseClasseIdRoute: typeof VerifTravailClasseClasseIdRoute
  BilanClasseIndexRoute: typeof BilanClasseIndexRoute
  QrCodesIndexRoute: typeof QrCodesIndexRoute
  ApiPublicIcsTokenRoute: typeof ApiPublicIcsTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verif-travail': {
      id: '/verif-travail'
      path: '/verif-travail'
      fullPath: '/verif-travail'
      preLoaderRoute: typeof VerifTravailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verif-classeur': {
      id: '/verif-classeur'
      path: '/verif-classeur'
      fullPath: '/verif-classeur'
      preLoaderRoute: typeof VerifClasseurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivi': {
      id: '/suivi'
      path: '/suivi'
      fullPath: '/suivi'
      preLoaderRoute: typeof SuiviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-eleve': {
      id: '/scan-eleve'
      path: '/scan-eleve'
      fullPath: '/scan-eleve'
      preLoaderRoute: typeof ScanEleveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-export': {
      id: '/import-export'
      path: '/import-export'
      fullPath: '/import-export'
      preLoaderRoute: typeof ImportExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historique': {
      id: '/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof HistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emploi-du-temps': {
      id: '/emploi-du-temps'
      path: '/emploi-du-temps'
      fullPath: '/emploi-du-temps'
      preLoaderRoute: typeof EmploiDuTempsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aesh': {
      id: '/aesh'
      path: '/aesh'
      fullPath: '/aesh'
      preLoaderRoute: typeof AeshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/absences': {
      id: '/absences'
      path: '/absences'
      fullPath: '/absences'
      preLoaderRoute: typeof AbsencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verif-travail/': {
      id: '/verif-travail/'
      path: '/'
      fullPath: '/verif-travail/'
      preLoaderRoute: typeof VerifTravailIndexRouteImport
      parentRoute: typeof VerifTravailRoute
    }
    '/verif-classeur/': {
      id: '/verif-classeur/'
      path: '/'
      fullPath: '/verif-classeur/'
      preLoaderRoute: typeof VerifClasseurIndexRouteImport
      parentRoute: typeof VerifClasseurRoute
    }
    '/qr-codes/': {
      id: '/qr-codes/'
      path: '/qr-codes'
      fullPath: '/qr-codes/'
      preLoaderRoute: typeof QrCodesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilan-classe/': {
      id: '/bilan-classe/'
      path: '/bilan-classe'
      fullPath: '/bilan-classe/'
      preLoaderRoute: typeof BilanClasseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verif-travail/$classeId': {
      id: '/verif-travail/$classeId'
      path: '/$classeId'
      fullPath: '/verif-travail/$classeId'
      preLoaderRoute: typeof VerifTravailClasseIdRouteImport
      parentRoute: typeof VerifTravailRoute
    }
    '/verif-travail-classe/$classeId': {
      id: '/verif-travail-classe/$classeId'
      path: '/verif-travail-classe/$classeId'
      fullPath: '/verif-travail-classe/$classeId'
      preLoaderRoute: typeof VerifTravailClasseClasseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verif-classeur/$classeId': {
      id: '/verif-classeur/$classeId'
      path: '/$classeId'
      fullPath: '/verif-classeur/$classeId'
      preLoaderRoute: typeof VerifClasseurClasseIdRouteImport
      parentRoute: typeof VerifClasseurRoute
    }
    '/qr-codes/$classeId': {
      id: '/qr-codes/$classeId'
      path: '/qr-codes/$classeId'
      fullPath: '/qr-codes/$classeId'
      preLoaderRoute: typeof QrCodesClasseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/$classeId': {
      id: '/plan/$classeId'
      path: '/plan/$classeId'
      fullPath: '/plan/$classeId'
      preLoaderRoute: typeof PlanClasseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eleves/$eleveId': {
      id: '/eleves/$eleveId'
      path: '/eleves/$eleveId'
      fullPath: '/eleves/$eleveId'
      preLoaderRoute: typeof ElevesEleveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/$classeId': {
      id: '/classes/$classeId'
      path: '/classes/$classeId'
      fullPath: '/classes/$classeId'
      preLoaderRoute: typeof ClassesClasseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilan/$eleveId': {
      id: '/bilan/$eleveId'
      path: '/bilan/$eleveId'
      fullPath: '/bilan/$eleveId'
      preLoaderRoute: typeof BilanEleveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilan-classe/$classeId': {
      id: '/bilan-classe/$classeId'
      path: '/bilan-classe/$classeId'
      fullPath: '/bilan-classe/$classeId'
      preLoaderRoute: typeof BilanClasseClasseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bavardages/$classeId': {
      id: '/bavardages/$classeId'
      path: '/bavardages/$classeId'
      fullPath: '/bavardages/$classeId'
      preLoaderRoute: typeof BavardagesClasseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appel/$classeId': {
      id: '/appel/$classeId'
      path: '/appel/$classeId'
      fullPath: '/appel/$classeId'
      preLoaderRoute: typeof AppelClasseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appel-plan/$classeId': {
      id: '/appel-plan/$classeId'
      path: '/appel-plan/$classeId'
      fullPath: '/appel-plan/$classeId'
      preLoaderRoute: typeof AppelPlanClasseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eleves/$eleveId/eleves/$nestedEleveId': {
      id: '/eleves/$eleveId/eleves/$nestedEleveId'
      path: '/eleves/$nestedEleveId'
      fullPath: '/eleves/$eleveId/eleves/$nestedEleveId'
      preLoaderRoute: typeof ElevesEleveIdElevesNestedEleveIdRouteImport
      parentRoute: typeof ElevesEleveIdRoute
    }
    '/api/public/ics/$token': {
      id: '/api/public/ics/$token'
      path: '/api/public/ics/$token'
      fullPath: '/api/public/ics/$token'
      preLoaderRoute: typeof ApiPublicIcsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface VerifClasseurRouteChildren {
  VerifClasseurClasseIdRoute: typeof VerifClasseurClasseIdRoute
  VerifClasseurIndexRoute: typeof VerifClasseurIndexRoute
}

const VerifClasseurRouteChildren: VerifClasseurRouteChildren = {
  VerifClasseurClasseIdRoute: VerifClasseurClasseIdRoute,
  VerifClasseurIndexRoute: VerifClasseurIndexRoute,
}

const VerifClasseurRouteWithChildren = VerifClasseurRoute._addFileChildren(
  VerifClasseurRouteChildren,
)

interface VerifTravailRouteChildren {
  VerifTravailClasseIdRoute: typeof VerifTravailClasseIdRoute
  VerifTravailIndexRoute: typeof VerifTravailIndexRoute
}

const VerifTravailRouteChildren: VerifTravailRouteChildren = {
  VerifTravailClasseIdRoute: VerifTravailClasseIdRoute,
  VerifTravailIndexRoute: VerifTravailIndexRoute,
}

const VerifTravailRouteWithChildren = VerifTravailRoute._addFileChildren(
  VerifTravailRouteChildren,
)

interface ElevesEleveIdRouteChildren {
  ElevesEleveIdElevesNestedEleveIdRoute: typeof ElevesEleveIdElevesNestedEleveIdRoute
}

const ElevesEleveIdRouteChildren: ElevesEleveIdRouteChildren = {
  ElevesEleveIdElevesNestedEleveIdRoute: ElevesEleveIdElevesNestedEleveIdRoute,
}

const ElevesEleveIdRouteWithChildren = ElevesEleveIdRoute._addFileChildren(
  ElevesEleveIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbsencesRoute: AbsencesRoute,
  AeshRoute: AeshRoute,
  EmploiDuTempsRoute: EmploiDuTempsRoute,
  HistoriqueRoute: HistoriqueRoute,
  ImportExportRoute: ImportExportRoute,
  ScanRoute: ScanRoute,
  ScanEleveRoute: ScanEleveRoute,
  SuiviRoute: SuiviRoute,
  VerifClasseurRoute: VerifClasseurRouteWithChildren,
  VerifTravailRoute: VerifTravailRouteWithChildren,
  AppelPlanClasseIdRoute: AppelPlanClasseIdRoute,
  AppelClasseIdRoute: AppelClasseIdRoute,
  BavardagesClasseIdRoute: BavardagesClasseIdRoute,
  BilanClasseClasseIdRoute: BilanClasseClasseIdRoute,
  BilanEleveIdRoute: BilanEleveIdRoute,
  ClassesClasseIdRoute: ClassesClasseIdRoute,
  ElevesEleveIdRoute: ElevesEleveIdRouteWithChildren,
  PlanClasseIdRoute: PlanClasseIdRoute,
  QrCodesClasseIdRoute: QrCodesClasseIdRoute,
  VerifTravailClasseClasseIdRoute: VerifTravailClasseClasseIdRoute,
  BilanClasseIndexRoute: BilanClasseIndexRoute,
  QrCodesIndexRoute: QrCodesIndexRoute,
  ApiPublicIcsTokenRoute: ApiPublicIcsTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
